FROM    debian:bullseye

RUN apt update -y && apt upgrade -y && apt-get install mariadb-server -y

RUN     mkdir /run/mysqld 

COPY entrypoint.sh /docker-entrypoint-initdb.d/entrypoint.sh

COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf
RUN  chown -R mysql:root /var/lib/mysql

RUN chmod +x /docker-entrypoint-initdb.d/entrypoint.sh

ENTRYPOINT  ["sh", "/docker-entrypoint-initdb.d/entrypoint.sh"]
