services:

  mariadb:
      build:
        context: ./mariadb
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      restart: unless-stopped
      expose:
        - "3306"
      networks:
        - inception


  wordpress:
      container_name: wordpress
      env_file: .env
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      build:
        context: wordpress
      depends_on:
        - mariadb
      restart: on-failure
      expose:
        - "9000"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

    

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/vlaggoun/data/wordpress"
  mariadb:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "/home/vlaggoun/data/database"

networks:
  inception:
    name: inception
    driver: bridge