FROM    debian:bullseye

RUN     apt update -y && apt upgrade -y && apt install -y wget

RUN     apt install -y php7.4 && apt install -y php-fpm && apt install -y php-mysql && apt install -y mariadb-client

RUN     wget https://fr.wordpress.org/wordpress-6.8-fr_FR.tar.gz -P /var/www/wordpress

RUN		chown -R root:root /var/www/wordpress

COPY    entrypoint.sh /usr/local/bin/entrypoint.sh

RUN     chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT  ["sh", "/usr/local/bin/entrypoint.sh"]